-- Creación de la base de datos y uso
CREATE DATABASE inventoryDB;
USE inventoryDB;

-- Creación de tablas
CREATE TABLE CATEGORY(
ID_CATEGORIA INT(10) AUTO_INCREMENT,
NOMBRE_CATEGORIA VARCHAR(100),
PRIMARY KEY (ID_CATEGORIA)
);
CREATE TABLE PRODUCT(
ID_PRODUCTO INT(10) AUTO_INCREMENT,
NOMBRE_PRODUCTO VARCHAR(250),
MARCA_PRODUCTO VARCHAR(100),
PRECIO_PRODUCTO INT(8),
CANTIDAD_PRODUCTO INT(4),
FECHA_REGISTRO_PRODUCTO DATETIME,
CATEGORY_ID_CATEGORIA INT(10),
PRIMARY KEY (ID_PRODUCTO),
FOREIGN KEY (CATEGORY_ID_CATEGORIA) REFERENCES CATEGORY(ID_CATEGORIA)
);

-- Datos de prueba

INSERT INTO CATEGORY (NOMBRE_CATEGORIA) VALUES ('PCs de Escritorio');
INSERT INTO CATEGORY (NOMBRE_CATEGORIA) VALUES ('Notebooks/Laptops');
INSERT INTO CATEGORY (NOMBRE_CATEGORIA) VALUES ('Celulares');
INSERT INTO CATEGORY (NOMBRE_CATEGORIA) VALUES ('Tablets');

INSERT INTO PRODUCT (NOMBRE_PRODUCTO, MARCA_PRODUCTO, PRECIO_PRODUCTO, FECHA_REGISTRO_PRODUCTO, CATEGORY_ID_CATEGORIA) VALUES ('Galaxy A20s', 'Samsung', 139990, CONVERT_TZ(NOW(), '+00:00', '-03:00'), 3);
INSERT INTO PRODUCT (NOMBRE_PRODUCTO, MARCA_PRODUCTO, PRECIO_PRODUCTO, FECHA_REGISTRO_PRODUCTO, CATEGORY_ID_CATEGORIA) VALUES ('Redmi Note 11', 'Xiaomi', 159990, CONVERT_TZ(NOW(), '+00:00', '-03:00'), 3);
INSERT INTO PRODUCT (NOMBRE_PRODUCTO, MARCA_PRODUCTO, PRECIO_PRODUCTO, FECHA_REGISTRO_PRODUCTO, CATEGORY_ID_CATEGORIA) VALUES ('TUF Gaming F15', 'Asus', 649990, CONVERT_TZ(NOW(), '+00:00', '-03:00'), 2);
INSERT INTO PRODUCT (NOMBRE_PRODUCTO, MARCA_PRODUCTO, PRECIO_PRODUCTO, FECHA_REGISTRO_PRODUCTO, CATEGORY_ID_CATEGORIA) VALUES ('Galaxy Tab S9', 'Samsung', 499990, CONVERT_TZ(NOW(), '+00:00', '-03:00'), 4);

-- Cambio a hora chilena: CONVERT_TZ(NOW(),'+00:00', '-03:00');