CREATE TABLE CATEGORY (
    ID_CATEGORIA INTEGER PRIMARY KEY AUTOINCREMENT,
    NOMBRE_CATEGORIA TEXT
);

CREATE TABLE PRODUCT (
    ID_PRODUCTO INTEGER PRIMARY KEY AUTOINCREMENT,
    NOMBRE_PRODUCTO TEXT,
    MARCA_PRODUCTO TEXT,
    PRECIO_PRODUCTO INTEGER,
    CANTIDAD_PRODUCTO INTEGER,
    FECHA_REGISTRO_PRODUCTO DATETIME,
    CATEGORY_ID_CATEGORIA INTEGER,
    FOREIGN KEY (CATEGORY_ID_CATEGORIA) REFERENCES CATEGORY(ID_CATEGORIA)
);

INSERT INTO CATEGORY (NOMBRE_CATEGORIA) VALUES ('PCs de Escritorio');
INSERT INTO CATEGORY (NOMBRE_CATEGORIA) VALUES ('Notebooks/Laptops');
INSERT INTO CATEGORY (NOMBRE_CATEGORIA) VALUES ('Celulares');
INSERT INTO CATEGORY (NOMBRE_CATEGORIA) VALUES ('Tablets');

INSERT INTO PRODUCT (NOMBRE_PRODUCTO, MARCA_PRODUCTO, PRECIO_PRODUCTO, FECHA_REGISTRO_PRODUCTO, CATEGORY_ID_CATEGORIA)
VALUES ('Galaxy A20s', 'Samsung', 139990, DATETIME('now', '-3 hours'), 3);
INSERT INTO PRODUCT (NOMBRE_PRODUCTO, MARCA_PRODUCTO, PRECIO_PRODUCTO, FECHA_REGISTRO_PRODUCTO, CATEGORY_ID_CATEGORIA)
VALUES ('Redmi Note 11', 'Xiaomi', 159990, DATETIME('now', '-3 hours'), 3);
INSERT INTO PRODUCT (NOMBRE_PRODUCTO, MARCA_PRODUCTO, PRECIO_PRODUCTO, FECHA_REGISTRO_PRODUCTO, CATEGORY_ID_CATEGORIA)
VALUES ('TUF Gaming F15', 'Asus', 649990, DATETIME('now', '-3 hours'), 2);
INSERT INTO PRODUCT (NOMBRE_PRODUCTO, MARCA_PRODUCTO, PRECIO_PRODUCTO, FECHA_REGISTRO_PRODUCTO, CATEGORY_ID_CATEGORIA)
VALUES ('Galaxy Tab S9', 'Samsung', 499990, DATETIME('now', '-3 hours'), 4);